

[language-server.godot]
command = "ncat" # or nc
args = [ "127.0.0.1", "6005"]

[[language]]
name = "gdscript"
language-servers = ["godot"]

[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]

[[language]]
name = "html"
roots = [".git"]
language-servers = [ "vscode-html-language-server","emmet-lsp"]
